### ISSUE TITLE
Request textDocument/documentSymbol failed.

### ISSUE THREAD

**Issue by 0xc0ffea** [jyaoma/vscode-lsl#1]
VSCode 1.89.0 Linux

![image](https://github.com/jyaoma/vscode-lsl/assets/7412721/c00c5666-05c5-4bd5-b8b4-f53094fd662c)

open following LSL from inventory

```
vector  alignment;
vector  targetVector;
integer travelDistance;
integer numListen;
integer targetFloor = -1;
list    floorHeights = [37.03310, 52.15938, 59.35120];
float   fixedFloorHeight = -1; //Set to floor heights, or set to -1 to use floorHeights list
float   speed = 0.25; //Valid values are 0.01 to 1.0, a Percentage of maxSpeed;
float   maxSpeed = 32;
float   precision = 0.5;
integer autoSpeed = TRUE;
integer initialDistance;
integer commChannel = 6538559;
integer numListenPrivate;
integer TTL = 5;
float   lastCommand;
 
elevate (vector end)
{
    vector current = llGetPos();
    travelDistance = llRound(current.z-end.z);
    travelDistance = llAbs(travelDistance);
 
    if (autoSpeed)
    {
        if (travelDistance < (initialDistance / 2))
        {
            speed -= (precision * 2 / 50);
            if (speed < 0.25) 
              speed = 0.25;
        }
        else
        {
            speed += (precision / 25);
            if (speed > 1) 
              speed = 1;
        }
    }
    if (travelDistance > 30)
    {
        travelDistance = 30;
        if (end.z > current.z)
        {
            end.z = current.z + 30;
        }
        else
        {
            end.z = current.z - 30;
        }
    }
    float i = travelDistance/(maxSpeed*speed);
    llMoveToTarget(end,i);
}
 
GotoFloor (integer floor, key id)
{    

     llShout(78,"go phantom" );
    if (targetFloor != floor)
    {
        llSetStatus(STATUS_PHYSICS, TRUE);
        //llLoopSound("ElevatorNoises", 1);
 
        targetFloor = floor;
 
        if (fixedFloorHeight > 0)
        {
            targetVector = alignment;
            targetVector.z = alignment.z + (fixedFloorHeight * floor);
        }
        else
        {
            targetVector = alignment;
            targetVector.z = llList2Float(floorHeights, floor);
        }
 
        vector current = llGetPos();
        initialDistance = llRound(current.z-targetVector.z);
        initialDistance = llAbs(initialDistance);
 
        if (autoSpeed)
        {
            speed = 0.01;
        }
 
      // llSay(0, "Heading for Floor # " + (string)targetFloor + "[" + (string)targetVector.z + "]");
        elevate(targetVector);
        llSetTimerEvent(precision);
    }
}
 
reset()
{
    llSay(0, "Resetting Elevator...");
    llSetStatus(STATUS_ROTATE_X| STATUS_ROTATE_Y| STATUS_ROTATE_Z, FALSE);
 
    alignment = llGetPos();
    llSetStatus(STATUS_PHYSICS, FALSE);

    llStopSound();
    lastCommand = llGetTimeOfDay();
    llListenRemove(numListen);
    numListen = llListen( 7, "", NULL_KEY, "");
}
default 
{
    state_entry()
    {
        reset();
    }
    on_rez(integer start_param)
    {
        reset();
        if (start_param > 0)
        {
            commChannel = start_param;
            llListenRemove(numListenPrivate);
            numListenPrivate = llListen(commChannel, "", NULL_KEY, "");
        }
    }
    listen(integer a, string n, key id, string m) 
    { 
        vector  pos;
        integer Floor;
        float   tempFloat;
        list    tempList;
        float   timeStamp;
        integer index;
        string  command;
        string  data;
        float   timediff;
 
        timediff = (llGetTimeOfDay() - lastCommand);
        if ((a == commChannel)&&(timediff > TTL))
        {
            lastCommand = llGetTimeOfDay();
            //Separate out incoming data
            tempList  = llCSV2List(m);
            timeStamp = llList2Float(tempList, 0);
            index     = llList2Integer(tempList, 1);
            command   = llList2String(tempList, 2);
            data      = llList2String(tempList, 3);
 
            //If public command then extract message
            if ((index == -2) && (command == "pub"))
            {
                m = data;
            }
        }
 
        if (llSubStringIndex(m, "goto floor") == 0)
        {
            llSay(78, "true");
            Floor = (integer)llGetSubString(m, 10, llStringLength(m));
            GotoFloor(Floor, NULL_KEY);
        }
        if (llSubStringIndex(m, "speed") == 0)
        {
            tempFloat = (float)llGetSubString(m, 5, llStringLength(m));
            if ((tempFloat > 0.001) && (tempFloat <= 1.0))
            {
                speed = tempFloat;
            }
        }
        if ((m=="elevator reset") && (id==llGetOwner()))
        {
            reset();
        }        
    } 
 
    timer()
    {
        vector CurrentPos;
        float tempfloat;
 
        CurrentPos = llGetPos();
        tempfloat = (CurrentPos.z - targetVector.z);
 
        if (llFabs(tempfloat) < 2) 
        {
            if (llFabs(tempfloat) < 0.05) 
            {
                //Arrived at Floor
                llWhisper(0, "Arrived at floor #" + (string)targetFloor);
                llShout(78,"go physical" );
                llSay(78, "false");
                llSetTimerEvent(0); 
                llSetStatus(STATUS_PHYSICS, FALSE);
                llStopSound();
            }
            else
            {
                llMoveToTarget(targetVector,1.0);
            }
        }
        else 
        {
            if (fixedFloorHeight > 0)
            {
                targetVector = alignment;
                targetVector.z = alignment.z + (fixedFloorHeight * targetFloor);
            }
            else
            {
                targetVector = alignment;
                targetVector.z = llList2Float(floorHeights, targetFloor);
            }
            elevate(targetVector);
        }
    }
}
```

Get following output

```
{
  ':0': {
    name: '',
    type: 'vector',
    line: 0,
    columnWithType: 0,
    column: 0,
    references: [
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      ... 660 more items
    ]
  },
  ':1': {
    name: '',
    type: 'vector',
    line: 1,
    columnWithType: 0,
    column: 0,
    references: [
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      ... 656 more items
    ]
  },
  'travelDistance:2': {
    name: 'travelDistance',
    type: 'integer',
    line: 2,
    columnWithType: 0,
    column: 8,
    references: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object]
    ]
  },
  'numListen:3': {
    name: 'numListen',
    type: 'integer',
    line: 3,
    columnWithType: 0,
    column: 8,
    references: [ [Object], [Object] ]
  },
  'targetFloor:4': {
    name: 'targetFloor',
    type: 'integer',
    line: 4,
    columnWithType: 0,
    column: 8,
    references: [ [Object], [Object], [Object], [Object], [Object] ]
  },
  ':5': {
    name: '',
    type: 'list',
    line: 5,
    columnWithType: 0,
    column: 0,
    references: [
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      ... 638 more items
    ]
  },
  ':8': {
    name: '',
    type: 'float',
    line: 8,
    columnWithType: 0,
    column: 0,
    references: [
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      ... 622 more items
    ]
  },
  ':9': {
    name: '',
    type: 'float',
    line: 9,
    columnWithType: 0,
    column: 0,
    references: [
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      ... 616 more items
    ]
  },
  'autoSpeed:10': {
    name: 'autoSpeed',
    type: 'integer',
    line: 10,
    columnWithType: 0,
    column: 8,
    references: [ [Object], [Object] ]
  },
  'initialDistance:11': {
    name: 'initialDistance',
    type: 'integer',
    line: 11,
    columnWithType: 0,
    column: 8,
    references: [ [Object], [Object], [Object], [Object] ]
  },
  'commChannel:12': {
    name: 'commChannel',
    type: 'integer',
    line: 12,
    columnWithType: 0,
    column: 8,
    references: [ [Object], [Object], [Object] ]
  },
  'numListenPrivate:13': {
    name: 'numListenPrivate',
    type: 'integer',
    line: 13,
    columnWithType: 0,
    column: 8,
    references: [ [Object], [Object] ]
  },
  'TTL:14': {
    name: 'TTL',
    type: 'integer',
    line: 14,
    columnWithType: 0,
    column: 8,
    references: [ [Object] ]
  },
  ':15': {
    name: '',
    type: 'float',
    line: 15,
    columnWithType: 0,
    column: 0,
    references: [
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      ... 582 more items
    ]
  },
  'end:17': {
    name: 'end',
    type: 'vector',
    line: 17,
    columnWithType: 9,
    column: 16,
    references: [ [Object], [Object], [Object], [Object], [Object] ]
  },
  'current:19': {
    name: 'current',
    type: 'vector',
    line: 19,
    columnWithType: 4,
    column: 11,
    references: [ [Object], [Object], [Object], [Object] ]
  },
  'i:50': {
    name: 'i',
    type: 'float',
    line: 50,
    columnWithType: 4,
    column: 10,
    references: [ [Object] ]
  },
  'floor:54': {
    name: 'floor',
    type: 'integer',
    line: 54,
    columnWithType: 11,
    column: 19,
    references: [ [Object], [Object], [Object], [Object] ]
  },
  'id:54': {
    name: 'id',
    type: 'key',
    line: 54,
    columnWithType: 26,
    column: 30,
    references: [ [Object], [Object] ]
  },
  'current:76': {
    name: 'current',
    type: 'vector',
    line: 76,
    columnWithType: 8,
    column: 15,
    references: [ [Object] ]
  },
  'start_param:110': {
    name: 'start_param',
    type: 'integer',
    line: 110,
    columnWithType: 11,
    column: 19,
    references: [ [Object], [Object] ]
  },
  'a:120': {
    name: 'a',
    type: 'integer',
    line: 120,
    columnWithType: 11,
    column: 19,
    references: [ [Object] ]
  },
  'n:120': {
    name: 'n',
    type: 'string',
    line: 120,
    columnWithType: 22,
    column: 29,
    references: []
  },
  'id:120': {
    name: 'id',
    type: 'key',
    line: 120,
    columnWithType: 32,
    column: 36,
    references: [ [Object] ]
  },
  'm:120': {
    name: 'm',
    type: 'string',
    line: 120,
    columnWithType: 40,
    column: 47,
    references: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object]
    ]
  },
  ':122': {
    name: '',
    type: 'vector',
    line: 122,
    columnWithType: 8,
    column: 8,
    references: [
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      ... 92 more items
    ]
  },
  'Floor:123': {
    name: 'Floor',
    type: 'integer',
    line: 123,
    columnWithType: 8,
    column: 16,
    references: [ [Object], [Object] ]
  },
  ':124': {
    name: '',
    type: 'float',
    line: 124,
    columnWithType: 8,
    column: 8,
    references: [
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      ... 84 more items
    ]
  },
  ':125': {
    name: '',
    type: 'list',
    line: 125,
    columnWithType: 8,
    column: 8,
    references: [
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      ... 80 more items
    ]
  },
  ':126': {
    name: '',
    type: 'float',
    line: 126,
    columnWithType: 8,
    column: 8,
    references: [
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      ... 76 more items
    ]
  },
  'index:127': {
    name: 'index',
    type: 'integer',
    line: 127,
    columnWithType: 8,
    column: 16,
    references: [ [Object], [Object] ]
  },
  ':128': {
    name: '',
    type: 'string',
    line: 128,
    columnWithType: 8,
    column: 8,
    references: [
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      ... 68 more items
    ]
  },
  ':129': {
    name: '',
    type: 'string',
    line: 129,
    columnWithType: 8,
    column: 8,
    references: [
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      ... 64 more items
    ]
  },
  ':130': {
    name: '',
    type: 'float',
    line: 130,
    columnWithType: 8,
    column: 8,
    references: [
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      ... 60 more items
    ]
  },
  'CurrentPos:172': {
    name: 'CurrentPos',
    type: 'vector',
    line: 172,
    columnWithType: 8,
    column: 15,
    references: [ [Object], [Object] ]
  },
  'tempfloat:173': {
    name: 'tempfloat',
    type: 'float',
    line: 173,
    columnWithType: 8,
    column: 14,
    references: [ [Object], [Object], [Object] ]
  }
}
{
  'd:0': {
    name: 'd',
    type: 'integer',
    line: 0,
    columnWithType: 0,
    column: 8,
    references: []
  },
  'p:1': {
    name: 'p',
    type: 'integer',
    line: 1,
    columnWithType: 0,
    column: 8,
    references: []
  },
  'x:9': {
    name: 'x',
    type: 'integer',
    line: 9,
    columnWithType: 8,
    column: 16,
    references: []
  },
  'i:10': {
    name: 'i',
    type: 'integer',
    line: 10,
    columnWithType: 8,
    column: 16,
    references: []
  },
  'total_number:14': {
    name: 'total_number',
    type: 'integer',
    line: 14,
    columnWithType: 16,
    column: 24,
    references: []
  }
}
[Error - 12:43:52 AM] Request textDocument/documentSymbol failed.
Error: name must not be falsy
	at r.validate (/opt/vscode/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:151:17855)
	at new r (/opt/vscode/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:151:18150)
	at asDocumentSymbol (/home/coffea/.vscode/extensions/jyaoma.lsl-lsp-1.0.5/client/node_modules/vscode-languageclient/lib/common/protocolConverter.js:604:22)
	at asDocumentSymbol (/home/coffea/.vscode/extensions/jyaoma.lsl-lsp-1.0.5/client/node_modules/vscode-languageclient/lib/common/protocolConverter.js:609:31)
	at asDocumentSymbol (/home/coffea/.vscode/extensions/jyaoma.lsl-lsp-1.0.5/client/node_modules/vscode-languageclient/lib/common/protocolConverter.js:609:31)
	at convertBatch (/home/coffea/.vscode/extensions/jyaoma.lsl-lsp-1.0.5/client/node_modules/vscode-languageclient/lib/common/utils/async.js:193:25)
	at Object.map (/home/coffea/.vscode/extensions/jyaoma.lsl-lsp-1.0.5/client/node_modules/vscode-languageclient/lib/common/utils/async.js:202:17)
	at Object.asDocumentSymbols (/home/coffea/.vscode/extensions/jyaoma.lsl-lsp-1.0.5/client/node_modules/vscode-languageclient/lib/common/protocolConverter.js:601:22)
	at _provideDocumentSymbols (/home/coffea/.vscode/extensions/jyaoma.lsl-lsp-1.0.5/client/node_modules/vscode-languageclient/lib/common/documentSymbol.js:83:76)
	at async r.provideDocumentSymbols (/opt/vscode/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:153:90654)
[Error - 12:43:54 AM] Request textDocument/documentSymbol failed.
Error: name must not be falsy
	at r.validate (/opt/vscode/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:151:17855)
	at new r (/opt/vscode/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:151:18150)
	at asDocumentSymbol (/home/coffea/.vscode/extensions/jyaoma.lsl-lsp-1.0.5/client/node_modules/vscode-languageclient/lib/common/protocolConverter.js:604:22)
	at asDocumentSymbol (/home/coffea/.vscode/extensions/jyaoma.lsl-lsp-1.0.5/client/node_modules/vscode-languageclient/lib/common/protocolConverter.js:609:31)
	at asDocumentSymbol (/home/coffea/.vscode/extensions/jyaoma.lsl-lsp-1.0.5/client/node_modules/vscode-languageclient/lib/common/protocolConverter.js:609:31)
	at convertBatch (/home/coffea/.vscode/extensions/jyaoma.lsl-lsp-1.0.5/client/node_modules/vscode-languageclient/lib/common/utils/async.js:193:25)
	at Object.map (/home/coffea/.vscode/extensions/jyaoma.lsl-lsp-1.0.5/client/node_modules/vscode-languageclient/lib/common/utils/async.js:202:17)
	at Object.asDocumentSymbols (/home/coffea/.vscode/extensions/jyaoma.lsl-lsp-1.0.5/client/node_modules/vscode-languageclient/lib/common/protocolConverter.js:601:22)
	at _provideDocumentSymbols (/home/coffea/.vscode/extensions/jyaoma.lsl-lsp-1.0.5/client/node_modules/vscode-languageclient/lib/common/documentSymbol.js:83:76)
	at async r.provideDocumentSymbols (/opt/vscode/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:153:90654)

```

**Comment by 0xc0ffea** [comment]
Sorry this isn't narrowed down any

**Comment by jyaoma** [comment]
I just released an update which should fix the issue! Thank you for reporting it!
