### ISSUE TITLE
Request textDocument/completion failed

### ISSUE THREAD

**Issue by Martin-Pitt** [jyaoma/vscode-lsl#9]
I keep getting these errors very frequently so decided to open an issue on this since it's pretty annoying.

<details>
<summary>LSL Script</summary>
Not really specific to this script but just an example. Happens with most or all my LSL scripts.

```lsl
#define TEXTURE_PROGRESS "10b15206-6a1b-7170-3368-2bd73fcc5ba6" // Texture for the sliding progress bar, assumes left half is solid and right half is transparent
#define LINK_PROGRESS LINK_THIS // Link number to use to target the progress bar prim, for this example we assume the link number the script is in, you should replace this with a global variable instead of a #define where you search the prim in linkset via name or description to identify it on script startup

// This function draws the progress bar as primitive params list that can be inserted into a llSetLinkPrimitiveParamsFast call. The reason to return a list so that you can batch other primitive params together for performant batched rendering
list progressBar(float progress, float delta, float total)
{
    // Convert down to 0.0-1.0 range
    progress /= total;
    delta /= total;
    
    // Show the subtraction bar
    if(delta < 0.0)
    {
        delta = progress - delta;
    }
    
    // Show addition bar
    else if(delta > 0.0)
    {
        delta = progress;
        progress -= delta;
    }
    
    if(progress < 0.0) progress = 0.0; else if(progress > 1.0) progress = 1.0;
    
    list params = [
        PRIM_LINK_TARGET, LINK_PROGRESS,
        PRIM_TEXTURE, 0, TEXTURE_PROGRESS, <.5, 1, 0>, <.25 - progress * .5, 0, 0>, 0,
        PRIM_TEXTURE, 1, TEXTURE_PROGRESS, <.5, 1, 0>, <.25 - delta * .5, 0, 0>, 0
    ];
    
    return params;
}


default
{
    state_entry()
    {
        llSetTimerEvent(0.1);
    }
    
    timer()
    {
        float progress = 25.0;
        float delta = 0.0;
        float total = 100.0;
        llSetLinkPrimitiveParamsFast(0, progressBar(progress, delta, total));
    }
}
```
</details>

Output:
<details>
<summary>Output</summary>

```
[Error - 3:23:05 PM] Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: Cannot read properties of undefined (reading 'match')
  Code: -32603 
{
  'TEXTURE_PROGRESS:0': {
    name: 'TEXTURE_PROGRESS',
    type: '',
    line: 0,
    columnWithType: 0,
    column: 8,
    references: [ [Object], [Object] ]
  },
  'LINK_PROGRESS:1': {
    name: 'LINK_PROGRESS',
    type: '',
    line: 1,
    columnWithType: 0,
    column: 8,
    references: [ [Object] ]
  },
  'progress:4': {
    name: 'progress',
    type: 'float',
    line: 4,
    columnWithType: 17,
    column: 23,
    references: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object]
    ]
  },
  'delta:4': {
    name: 'delta',
    type: 'float',
    line: 4,
    columnWithType: 33,
    column: 39,
    references: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object]
    ]
  },
  'total:4': {
    name: 'total',
    type: 'float',
    line: 4,
    columnWithType: 46,
    column: 52,
    references: [ [Object], [Object], [Object], [Object] ]
  },
  'params:25': {
    name: 'params',
    type: 'list',
    line: 25,
    columnWithType: 4,
    column: 9,
    references: [ [Object] ]
  },
  'progress:47': {
    name: 'progress',
    type: 'float',
    line: 47,
    columnWithType: 8,
    column: 14,
    references: [ [Object] ]
  },
  'delta:48': {
    name: 'delta',
    type: 'float',
    line: 48,
    columnWithType: 8,
    column: 14,
    references: [ [Object] ]
  },
  'total:49': {
    name: 'total',
    type: 'float',
    line: 49,
    columnWithType: 8,
    column: 14,
    references: [ [Object] ]
  }
}
{
  'TEXTURE_PROGRESS:0': {
    name: 'TEXTURE_PROGRESS',
    type: '',
    line: 0,
    columnWithType: 0,
    column: 8,
    references: [ [Object], [Object] ]
  },
  'LINK_PROGRESS:1': {
    name: 'LINK_PROGRESS',
    type: '',
    line: 1,
    columnWithType: 0,
    column: 8,
    references: [ [Object] ]
  },
  'progress:4': {
    name: 'progress',
    type: 'float',
    line: 4,
    columnWithType: 17,
    column: 23,
    references: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object]
    ]
  },
  'delta:4': {
    name: 'delta',
    type: 'float',
    line: 4,
    columnWithType: 33,
    column: 39,
    references: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object]
    ]
  },
  'total:4': {
    name: 'total',
    type: 'float',
    line: 4,
    columnWithType: 46,
    column: 52,
    references: [ [Object], [Object], [Object], [Object] ]
  },
  'params:25': {
    name: 'params',
    type: 'list',
    line: 25,
    columnWithType: 4,
    column: 9,
    references: [ [Object] ]
  },
  'progress:47': {
    name: 'progress',
    type: 'float',
    line: 47,
    columnWithType: 8,
    column: 14,
    references: [ [Object] ]
  },
  'delta:48': {
    name: 'delta',
    type: 'float',
    line: 48,
    columnWithType: 8,
    column: 14,
    references: [ [Object] ]
  },
  'total:49': {
    name: 'total',
    type: 'float',
    line: 49,
    columnWithType: 8,
    column: 14,
    references: [ [Object] ]
  }
}
{
  'TEXTURE_PROGRESS:0': {
    name: 'TEXTURE_PROGRESS',
    type: '',
    line: 0,
    columnWithType: 0,
    column: 8,
    references: [ [Object], [Object] ]
  },
  'LINK_PROGRESS:1': {
    name: 'LINK_PROGRESS',
    type: '',
    line: 1,
    columnWithType: 0,
    column: 8,
    references: [ [Object] ]
  },
  'progress:4': {
    name: 'progress',
    type: 'float',
    line: 4,
    columnWithType: 17,
    column: 23,
    references: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object]
    ]
  },
  'delta:4': {
    name: 'delta',
    type: 'float',
    line: 4,
    columnWithType: 33,
    column: 39,
    references: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object]
    ]
  },
  'total:4': {
    name: 'total',
    type: 'float',
    line: 4,
    columnWithType: 46,
    column: 52,
    references: [ [Object], [Object], [Object], [Object] ]
  },
  'params:25': {
    name: 'params',
    type: 'list',
    line: 25,
    columnWithType: 4,
    column: 9,
    references: [ [Object] ]
  },
  'progress:47': {
    name: 'progress',
    type: 'float',
    line: 47,
    columnWithType: 8,
    column: 14,
    references: [ [Object] ]
  },
  'delta:48': {
    name: 'delta',
    type: 'float',
    line: 48,
    columnWithType: 8,
    column: 14,
    references: [ [Object] ]
  },
  'total:49': {
    name: 'total',
    type: 'float',
    line: 49,
    columnWithType: 8,
    column: 14,
    references: [ [Object] ]
  }
}
{
  'TEXTURE_PROGRESS:0': {
    name: 'TEXTURE_PROGRESS',
    type: '',
    line: 0,
    columnWithType: 0,
    column: 8,
    references: [ [Object], [Object] ]
  },
  'LINK_PROGRESS:1': {
    name: 'LINK_PROGRESS',
    type: '',
    line: 1,
    columnWithType: 0,
    column: 8,
    references: [ [Object] ]
  },
  'progress:4': {
    name: 'progress',
    type: 'float',
    line: 4,
    columnWithType: 17,
    column: 23,
    references: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object]
    ]
  },
  'delta:4': {
    name: 'delta',
    type: 'float',
    line: 4,
    columnWithType: 33,
    column: 39,
    references: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object]
    ]
  },
  'total:4': {
    name: 'total',
    type: 'float',
    line: 4,
    columnWithType: 46,
    column: 52,
    references: [ [Object], [Object], [Object], [Object] ]
  },
  'params:25': {
    name: 'params',
    type: 'list',
    line: 25,
    columnWithType: 4,
    column: 9,
    references: [ [Object] ]
  },
  'progress:47': {
    name: 'progress',
    type: 'float',
    line: 47,
    columnWithType: 8,
    column: 14,
    references: [ [Object] ]
  },
  'delta:48': {
    name: 'delta',
    type: 'float',
    line: 48,
    columnWithType: 8,
    column: 14,
    references: [ [Object] ]
  },
  'total:49': {
    name: 'total',
    type: 'float',
    line: 49,
    columnWithType: 8,
    column: 14,
    references: [ [Object] ]
  }
}
{
  'TEXTURE_PROGRESS:0': {
    name: 'TEXTURE_PROGRESS',
    type: '',
    line: 0,
    columnWithType: 0,
    column: 8,
    references: [ [Object], [Object] ]
  },
  'LINK_PROGRESS:1': {
    name: 'LINK_PROGRESS',
    type: '',
    line: 1,
    columnWithType: 0,
    column: 8,
    references: [ [Object] ]
  },
  'progress:4': {
    name: 'progress',
    type: 'float',
    line: 4,
    columnWithType: 17,
    column: 23,
    references: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object]
    ]
  },
  'delta:4': {
    name: 'delta',
    type: 'float',
    line: 4,
    columnWithType: 33,
    column: 39,
    references: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object]
    ]
  },
  'total:4': {
    name: 'total',
    type: 'float',
    line: 4,
    columnWithType: 46,
    column: 52,
    references: [ [Object], [Object], [Object], [Object] ]
  },
  'params:25': {
    name: 'params',
    type: 'list',
    line: 25,
    columnWithType: 4,
    column: 9,
    references: [ [Object] ]
  },
  'progress:47': {
    name: 'progress',
    type: 'float',
    line: 47,
    columnWithType: 8,
    column: 14,
    references: [ [Object] ]
  },
  'delta:48': {
    name: 'delta',
    type: 'float',
    line: 48,
    columnWithType: 8,
    column: 14,
    references: [ [Object] ]
  },
  'total:49': {
    name: 'total',
    type: 'float',
    line: 49,
    columnWithType: 8,
    column: 14,
    references: [ [Object] ]
  }
}
{
  'TEXTURE_PROGRESS:0': {
    name: 'TEXTURE_PROGRESS',
    type: '',
    line: 0,
    columnWithType: 0,
    column: 8,
    references: [ [Object], [Object] ]
  },
  'LINK_PROGRESS:1': {
    name: 'LINK_PROGRESS',
    type: '',
    line: 1,
    columnWithType: 0,
    column: 8,
    references: [ [Object] ]
  },
  'progress:4': {
    name: 'progress',
    type: 'float',
    line: 4,
    columnWithType: 17,
    column: 23,
    references: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object]
    ]
  },
  'delta:4': {
    name: 'delta',
    type: 'float',
    line: 4,
    columnWithType: 33,
    column: 39,
    references: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object]
    ]
  },
  'total:4': {
    name: 'total',
    type: 'float',
    line: 4,
    columnWithType: 46,
    column: 52,
    references: [ [Object], [Object], [Object], [Object] ]
  },
  'params:25': {
    name: 'params',
    type: 'list',
    line: 25,
    columnWithType: 4,
    column: 9,
    references: [ [Object] ]
  },
  'progress:47': {
    name: 'progress',
    type: 'float',
    line: 47,
    columnWithType: 8,
    column: 14,
    references: [ [Object] ]
  },
  'delta:48': {
    name: 'delta',
    type: 'float',
    line: 48,
    columnWithType: 8,
    column: 14,
    references: [ [Object] ]
  },
  'total:49': {
    name: 'total',
    type: 'float',
    line: 49,
    columnWithType: 8,
    column: 14,
    references: [ [Object] ]
  }
}
{
  'TEXTURE_PROGRESS:0': {
    name: 'TEXTURE_PROGRESS',
    type: '',
    line: 0,
    columnWithType: 0,
    column: 8,
    references: [ [Object], [Object] ]
  },
  'LINK_PROGRESS:1': {
    name: 'LINK_PROGRESS',
    type: '',
    line: 1,
    columnWithType: 0,
    column: 8,
    references: [ [Object] ]
  },
  'progress:4': {
    name: 'progress',
    type: 'float',
    line: 4,
    columnWithType: 17,
    column: 23,
    references: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object]
    ]
  },
  'delta:4': {
    name: 'delta',
    type: 'float',
    line: 4,
    columnWithType: 33,
    column: 39,
    references: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object]
    ]
  },
  'total:4': {
    name: 'total',
    type: 'float',
    line: 4,
    columnWithType: 46,
    column: 52,
    references: [ [Object], [Object], [Object], [Object] ]
  },
  'params:25': {
    name: 'params',
    type: 'list',
    line: 25,
    columnWithType: 4,
    column: 9,
    references: [ [Object] ]
  },
  'progress:47': {
    name: 'progress',
    type: 'float',
    line: 47,
    columnWithType: 8,
    column: 14,
    references: [ [Object] ]
  },
  'delta:48': {
    name: 'delta',
    type: 'float',
    line: 48,
    columnWithType: 8,
    column: 14,
    references: [ [Object] ]
  },
  'total:49': {
    name: 'total',
    type: 'float',
    line: 49,
    columnWithType: 8,
    column: 14,
    references: [ [Object] ]
  }
}
{
  'TEXTURE_PROGRESS:0': {
    name: 'TEXTURE_PROGRESS',
    type: '',
    line: 0,
    columnWithType: 0,
    column: 8,
    references: [ [Object], [Object] ]
  },
  'LINK_PROGRESS:1': {
    name: 'LINK_PROGRESS',
    type: '',
    line: 1,
    columnWithType: 0,
    column: 8,
    references: [ [Object] ]
  },
  'progress:4': {
    name: 'progress',
    type: 'float',
    line: 4,
    columnWithType: 17,
    column: 23,
    references: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object]
    ]
  },
  'delta:4': {
    name: 'delta',
    type: 'float',
    line: 4,
    columnWithType: 33,
    column: 39,
    references: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object]
    ]
  },
  'total:4': {
    name: 'total',
    type: 'float',
    line: 4,
    columnWithType: 46,
    column: 52,
    references: [ [Object], [Object], [Object], [Object] ]
  },
  'params:25': {
    name: 'params',
    type: 'list',
    line: 25,
    columnWithType: 4,
    column: 9,
    references: [ [Object] ]
  },
  'progress:47': {
    name: 'progress',
    type: 'float',
    line: 47,
    columnWithType: 8,
    column: 14,
    references: [ [Object] ]
  },
  'delta:48': {
    name: 'delta',
    type: 'float',
    line: 48,
    columnWithType: 8,
    column: 14,
    references: [ [Object] ]
  },
  'total:49': {
    name: 'total',
    type: 'float',
    line: 49,
    columnWithType: 8,
    column: 14,
    references: [ [Object] ]
  }
}
{
  'TEXTURE_PROGRESS:0': {
    name: 'TEXTURE_PROGRESS',
    type: '',
    line: 0,
    columnWithType: 0,
    column: 8,
    references: [ [Object], [Object] ]
  },
  'LINK_PROGRESS:1': {
    name: 'LINK_PROGRESS',
    type: '',
    line: 1,
    columnWithType: 0,
    column: 8,
    references: [ [Object] ]
  },
  'progress:4': {
    name: 'progress',
    type: 'float',
    line: 4,
    columnWithType: 17,
    column: 23,
    references: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object]
    ]
  },
  'delta:4': {
    name: 'delta',
    type: 'float',
    line: 4,
    columnWithType: 33,
    column: 39,
    references: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object]
    ]
  },
  'total:4': {
    name: 'total',
    type: 'float',
    line: 4,
    columnWithType: 46,
    column: 52,
    references: [ [Object], [Object], [Object], [Object] ]
  },
  'params:25': {
    name: 'params',
    type: 'list',
    line: 25,
    columnWithType: 4,
    column: 9,
    references: [ [Object] ]
  },
  'progress:47': {
    name: 'progress',
    type: 'float',
    line: 47,
    columnWithType: 8,
    column: 14,
    references: [ [Object] ]
  },
  'delta:48': {
    name: 'delta',
    type: 'float',
    line: 48,
    columnWithType: 8,
    column: 14,
    references: [ [Object] ]
  },
  'total:49': {
    name: 'total',
    type: 'float',
    line: 49,
    columnWithType: 8,
    column: 14,
    references: [ [Object] ]
  }
}
[Error - 3:23:17 PM] Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: Cannot read properties of undefined (reading 'match')
  Code: -32603 
{
  'TEXTURE_PROGRESS:0': {
    name: 'TEXTURE_PROGRESS',
    type: '',
    line: 0,
    columnWithType: 0,
    column: 8,
    references: [ [Object], [Object] ]
  },
  'LINK_PROGRESS:1': {
    name: 'LINK_PROGRESS',
    type: '',
    line: 1,
    columnWithType: 0,
    column: 8,
    references: [ [Object] ]
  },
  'progress:4': {
    name: 'progress',
    type: 'float',
    line: 4,
    columnWithType: 17,
    column: 23,
    references: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object]
    ]
  },
  'delta:4': {
    name: 'delta',
    type: 'float',
    line: 4,
    columnWithType: 33,
    column: 39,
    references: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object]
    ]
  },
  'total:4': {
    name: 'total',
    type: 'float',
    line: 4,
    columnWithType: 46,
    column: 52,
    references: [ [Object], [Object], [Object], [Object] ]
  },
  'params:25': {
    name: 'params',
    type: 'list',
    line: 25,
    columnWithType: 4,
    column: 9,
    references: [ [Object] ]
  },
  'progress:36': {
    name: 'progress',
    type: 'float',
    line: 36,
    columnWithType: 0,
    column: 6,
    references: [ [Object], [Object] ]
  },
  'progress:47': {
    name: 'progress',
    type: 'float',
    line: 47,
    columnWithType: 8,
    column: 14,
    references: [ [Object] ]
  },
  'delta:48': {
    name: 'delta',
    type: 'float',
    line: 48,
    columnWithType: 8,
    column: 14,
    references: [ [Object] ]
  },
  'total:49': {
    name: 'total',
    type: 'float',
    line: 49,
    columnWithType: 8,
    column: 14,
    references: [ [Object] ]
  }
}
{
  'TEXTURE_PROGRESS:0': {
    name: 'TEXTURE_PROGRESS',
    type: '',
    line: 0,
    columnWithType: 0,
    column: 8,
    references: [ [Object], [Object] ]
  },
  'LINK_PROGRESS:1': {
    name: 'LINK_PROGRESS',
    type: '',
    line: 1,
    columnWithType: 0,
    column: 8,
    references: [ [Object] ]
  },
  'progress:4': {
    name: 'progress',
    type: 'float',
    line: 4,
    columnWithType: 17,
    column: 23,
    references: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object]
    ]
  },
  'delta:4': {
    name: 'delta',
    type: 'float',
    line: 4,
    columnWithType: 33,
    column: 39,
    references: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object]
    ]
  },
  'total:4': {
    name: 'total',
    type: 'float',
    line: 4,
    columnWithType: 46,
    column: 52,
    references: [ [Object], [Object], [Object], [Object] ]
  },
  'params:25': {
    name: 'params',
    type: 'list',
    line: 25,
    columnWithType: 4,
    column: 9,
    references: [ [Object] ]
  },
  'progress:36': {
    name: 'progress',
    type: 'float',
    line: 36,
    columnWithType: 0,
    column: 6,
    references: [ [Object], [Object] ]
  },
  'progress:47': {
    name: 'progress',
    type: 'float',
    line: 47,
    columnWithType: 8,
    column: 14,
    references: [ [Object] ]
  },
  'delta:48': {
    name: 'delta',
    type: 'float',
    line: 48,
    columnWithType: 8,
    column: 14,
    references: [ [Object] ]
  },
  'total:49': {
    name: 'total',
    type: 'float',
    line: 49,
    columnWithType: 8,
    column: 14,
    references: [ [Object] ]
  }
}
[Error - 3:23:18 PM] Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: Cannot read properties of undefined (reading 'match')
  Code: -32603 
```
</details>

**Comment by coren0327** [comment]
Similar issue:
TypeError: Cannot set properties of undefined (setting 'endLine')
    at c:\Users\NekoV\.vscode\extensions\jyaoma.lsl-lsp-1.1.8\server\out\scopes.js:74:55
    at Array.forEach (<anonymous>)
    at c:\Users\NekoV\.vscode\extensions\jyaoma.lsl-lsp-1.1.8\server\out\scopes.js:53:24
    at Array.forEach (<anonymous>)
    at getScopes (c:\Users\NekoV\.vscode\extensions\jyaoma.lsl-lsp-1.1.8\server\out\scopes.js:48:11)
    at scanDocument (c:\Users\NekoV\.vscode\extensions\jyaoma.lsl-lsp-1.1.8\server\out\scanner.js:15:44)
    at c:\Users\NekoV\.vscode\extensions\jyaoma.lsl-lsp-1.1.8\server\out\server.js:247:63
    at CallbackList.invoke (c:\Users\NekoV\.vscode\extensions\jyaoma.lsl-lsp-1.1.8\server\node_modules\vscode-jsonrpc\lib\common\events.js:55:39)
    at Emitter.fire (c:\Users\NekoV\.vscode\extensions\jyaoma.lsl-lsp-1.1.8\server\node_modules\vscode-jsonrpc\lib\common\events.js:117:36)
    at c:\Users\NekoV\.vscode\extensions\jyaoma.lsl-lsp-1.1.8\server\node_modules\vscode-languageserver\lib\common\textDocuments.js:122:38
{
  'blacklist_coms:0': {
    name: 'blacklist_coms',
    type: 'list',
    line: 0,
    columnWithType: 0,
    column: 5,
    references: [ [Object], [Object] ]
  },
  'close_connection_list:1': {
    name: 'close_connection_list',
    type: 'list',
    line: 1,
    columnWithType: 0,
    column: 5,
    references: [ [Object], [Object] ]
  },
  'current_gate:2': {
    name: 'current_gate',
    type: 'key',
    line: 2,
    columnWithType: 0,
    column: 4,
    references: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object]
    ]
  },
  'incchan:3': {
    name: 'incchan',
    type: 'integer',
    line: 3,
    columnWithType: 0,
    column: 8,
    references: [ [Object], [Object], [Object], [Object], [Object] ]
  },
  'health_check:4': {
    name: 'health_check',
    type: 'integer',
    line: 4,
    columnWithType: 0,
    column: 8,
    references: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object]
    ]
  },
  'last_known_status:5': {
    name: 'last_known_status',
    type: 'string',
    line: 5,
    columnWithType: 0,
    column: 7,
    references: [ [Object], [Object], [Object], [Object], [Object] ]
  },
  'previous_gate_key:6': {
    name: 'previous_gate_key',
    type: 'key',
    line: 6,
    columnWithType: 0,
    column: 4,
    references: [ [Object], [Object] ]
  },
  'gate_address:7': {
    name: 'gate_address',
    type: 'string',
    line: 7,
    columnWithType: 0,
    column: 7,
    references: [ [Object], [Object] ]
  },
  'chan:10': {
    name: 'chan',
    type: 'integer',
    line: 10,
    columnWithType: 13,
    column: 21,
    references: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object]
    ]
  },
  'pack:10': {
    name: 'pack',
    type: 'string',
    line: 10,
    columnWithType: 27,
    column: 34,
    references: [ [Object] ]
  },
  'id:10': {
    name: 'id',
    type: 'key',
    line: 10,
    columnWithType: 40,
    column: 44,
    references: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object]
    ]
  },
  'outp_chan:12': {
    name: 'outp_chan',
    type: 'integer',
    line: 12,
    columnWithType: 4,
    column: 12,
    references: [ [Object], [Object], [Object] ]
  },
  'chan:21': {
    name: 'chan',
    type: 'integer',
    line: 21,
    columnWithType: 13,
    column: 21,
    references: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object]
    ]
  },
  'msg:21': {
    name: 'msg',
    type: 'string',
    line: 21,
    columnWithType: 27,
    column: 34,
    references: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object]
    ]
  },
  'id:21': {
    name: 'id',
    type: 'key',
    line: 21,
    columnWithType: 39,
    column: 43,
    references: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object]
    ]
  },
  'data:23': {
    name: 'data',
    type: 'list',
    line: 23,
    columnWithType: 4,
    column: 9,
    references: [
      [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object]
    ]
  },
  'data_space:24': {
    name: 'data_space',
    type: 'list',
    line: 24,
    columnWithType: 4,
    column: 9,
    references: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object]
    ]
  },
  'package:25': {
    name: 'package',
    type: 'string',
    line: 25,
    columnWithType: 4,
    column: 11,
    references: [
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object]
    ]
  },
  'reason:154': {
    name: 'reason',
    type: 'string',
    line: 154,
    columnWithType: 13,
    column: 20,
    references: []
  },
  'sender_num:192': {
    name: 'sender_num',
    type: 'integer',
    line: 192,
    columnWithType: 17,
    column: 25,
    references: []
  },
  'num:192': {
    name: 'num',
    type: 'integer',
    line: 192,
    columnWithType: 37,
    column: 45,
    references: [ [Object], [Object], [Object], [Object] ]
  },
  'str:192': {
    name: 'str',
    type: 'string',
    line: 192,
    columnWithType: 50,
    column: 57,
    references: [ [Object], [Object], [Object], [Object], [Object], [Object] ]
  },
  'id:192': {
    name: 'id',
    type: 'key',
    line: 192,
    columnWithType: 62,
    column: 66,
    references: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object]
    ]
  },
  'data:200': {
    name: 'data',
    type: 'list',
    line: 200,
    columnWithType: 12,
    column: 17,
    references: [ [Object] ]
  },
  'tim:201': {
    name: 'tim',
    type: 'float',
    line: 201,
    columnWithType: 12,
    column: 18,
    references: [ [Object] ]
  },
  'chan:235': {
    name: 'chan',
    type: 'integer',
    line: 235,
    columnWithType: 11,
    column: 19,
    references: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object]
    ]
  },
  'name:235': {
    name: 'name',
    type: 'string',
    line: 235,
    columnWithType: 24,
    column: 31,
    references: []
  },
  'id:235': {
    name: 'id',
    type: 'key',
    line: 235,
    columnWithType: 36,
    column: 40,
    references: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object]
    ]
  },
  'msg:235': {
    name: 'msg',
    type: 'string',
    line: 235,
    columnWithType: 43,
    column: 50,
    references: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object]
    ]
  },
  'data:239': {
    name: 'data',
    type: 'list',
    line: 239,
    columnWithType: 12,
    column: 17,
    references: [ [Object], [Object] ]
  }
}
[Error - 4:02:48 PM] Request textDocument/documentSymbol failed.
  Message: Request textDocument/documentSymbol failed with message: Cannot set properties of undefined (setting 'endLine')
  Code: -32603 
[Error - 4:02:48 PM] Request textDocument/documentSymbol failed.
  Message: Request textDocument/documentSymbol failed with message: Cannot set properties of undefined (setting 'endLine')
  Code: -32603

**Comment by jyaoma** [comment]
Sorry that this has taken so long for me to get back to. I've made quite a few updates to this extension since you've created this issue, I may have fixed this issue already. If you see it again, please feel free to open another issue. Thanks.
